/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package se.vitberget.aoc.kafka

class App2 {
    val greeting: String
        get() {
            return "Hello World! app2"
        }
}

fun main() {
    println(App2().greeting)
}
