/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package se.vitberget.aoc.kafka

class App1 {
    val greeting: String
        get() {
            return "Hello World! app1"
        }
}

fun main() {
    println(App1().greeting)
}
