/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package se.vitberget.aoc.kafka

import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {
    val port = 8011
    println("PuzzleReceiver port: $port")
    embeddedServer(
        Netty,
        port = port,
        host = "0.0.0.0",
        watchPaths = listOf("classes")) {
        configureRouting()
    }.start(wait = true)
}
